### ISSUE TITLE
Plan to integrate C++ simulator

### ISSUE THREAD

**Issue by indisoluble** [QISKit/qiskit-sdk-swift#8]
Hi @manoelmarques,

I noticed this file: [QasmCppSimulator.swift](https://github.com/QISKit/qiskit-sdk-swift/blob/master/Sources/qiskit/backends/QasmCppSimulator.swift), is not implemented yet and I would like to do so.

As far as I can see, the C++ simulator referred in this file is the [qasm-simulator-cpp](https://github.com/QISKit/qiskit-sdk-py/tree/master/src/qasm-simulator-cpp) located in the Python repository.

Although it is possible to integrate C++ code inside a Xcode project and do the bridging from C++ to Swift with a C wrapper, a pure Swift package does not allow to mix languages. So, I was wondering if there is any plan about how to proceed or if suggestions are accepted :)

**Comment by indisoluble** [comment]
Hi again @manoelmarques 

Since my last comment I have been studying a few things, one among them is how to build a Debian package. The thing is that, given that a Swift package can not mix languages, the only alternative (as far as I can tell) for Linux/Ubuntu is to install the simulator as another app and then, call it from the Swift code. The easiest way to do so is with `apt-get`.

I am going to start to work on it, there are many things to do (apart from developing the package, at some point I will have to contact people in the Python project and also, if the idea is accepted, we will still need a sponsor to upload a package to Debian) but I would like to know what you thing about it.

Regards.

**Comment by manoelmarques** [comment]
Hi @indisoluble,

It seems feasible to me but it affects more the QISkit C++ side than Swift. You should contact the QISkit SDK Python project owners to see what they think about a simulator app in Ubuntu.

**Comment by indisoluble** [comment]
Done :)

By the way, the new Debian package is located here: https://github.com/indisoluble/qasm-simulator-cpp-debian-pkg

Regards.

**Comment by indisoluble** [comment]
Hi,

Sorry I kept this issue open for so long. I am already in contact with the owners of the Python project, so as soon as we have the debian package, I will prepare a new PR. But this issue is no longer useful so I am closing it.

Regards.
